dataset_source: "tapaco"
source_params:
  tapaco:
    language: "ru"
    pair_mode: "all_pairs"
  backtranslation:
    from_lang: "ru"
    to_lang: "en"
    batch_size: 100
    max_workers: 2
    max_requests_per_second: 0.5
    checkpoint_every: 25
    output_file: "data/backtranslated.parquet"
  #custom_merge:
  #  files: ["data/ds1.csv", "data/ds2.csv"]

preprocessing:
  steps:
    - normalize_text
    - remove_duplicates
    - filter_case_and_yo
    - filter_trivial_pairs
    - filter_length_ratio
    - filter_by_length
    - filter_grammar_only_changes
    - filter_paraphrase_score
    - filter_semantic_similarity
  normalize_text:
    trim: true
    remove_brackets: true
  remove_duplicates: {}
  filter_case_and_yo: {}
  filter_trivial_pairs:
    min_edit_ratio: 0.15
    max_edit_ratio: 0.85
    min_len: 5
    max_len: 128
  filter_length_ratio:
    min_ratio: 0.6
    max_ratio: 1.7
  filter_by_length:
    max_tokens: 128
    min_tokens: 5
    tokenizer: "cointegrated/rut5-base"
  filter_grammar_only_changes:
    min_gram_ratio: 0.8
  filter_paraphrase_score:
    threshold: 0.5
    model: "inkoziev/ruparaphrase_quality"
    batch_size: 32
  filter_semantic_similarity:
    min_threshold: 0.85
    max_threshold: 0.97
    model: "sentence-transformers/LaBSE"
    batch_size: 64

model_name: "rut5_paraphraser"
model_config:
  pretrained_name: "cointegrated/rut5-base"
  max_length: 128
  batch_size: 12
  learning_rate: 1e-4
  num_epochs: 5
  warmup_steps: 200
  weight_decay: 0.01
  gradient_accumulation_steps: 1

trainer_config:
  output_dir: "models/rut5_paraphraser/saves"
  batch_size: 12
  logging_strategy: "epoch"
  eval_strategy: "epoch"
  save_strategy: "epoch"
  save_total_limit: 3
  load_best_model_at_end: true
  metric_for_best_model: "eval_loss"
  greater_is_better: false
  fp16: false
  resume_from_checkpoint: true

metrics_config:
  metrics: ["bleu", "bertscore", "cosine_similarity"]
  bertscore_model: "cointegrated/rubert-tiny2"
  embedding_model: "sentence-transformers/LaBSE"
  batch_size: 8